`timescale 1ns/1ps

// =============================================================================
//  dwt_tb.sv — 1-D DWT Testbench
//  EventVault-R Accelerator — Phase C Verification
//
//  Reads golden vectors generated by the Python reference model (Phase A)
//  and verifies the Q16.16 RTL output matches within quantization tolerance.
// =============================================================================

module dwt_tb;

    // Clock and Reset
    logic clk;
    logic rst_n;

    // DUT Signals
    logic        in_valid;
    logic [31:0] in_data;  // Q16.16 format
    logic        in_last;
    logic        in_ready;

    logic        lo_valid;
    logic [31:0] lo_data;
    logic        lo_last;

    logic        hi_valid;
    logic [31:0] hi_data;
    logic        hi_last;

    // Clock Generation
    always #5 clk = ~clk;

    // Instantiate DUT
    dwt_1d_bior #(
        .Q_FRACT_W(16),
        .IN_W(32),
        .OUT_W(32)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .in_valid(in_valid),
        .in_data(in_data),
        .in_last(in_last),
        .in_ready(in_ready),
        .lo_valid(lo_valid),
        .lo_data(lo_data),
        .lo_last(lo_last),
        .hi_valid(hi_valid),
        .hi_data(hi_data),
        .hi_last(hi_last)
    );

    // Simulation Sequence
    initial begin
        clk = 0;
        rst_n = 0;
        in_valid = 0;
        in_data = 0;
        in_last = 0;

        // Reset
        #20 rst_n = 1;
        #10;

        // TODO: In Phase C C7 (Verification), add SystemVerilog code to:
        // 1. $fopen the `verification/vectors/image_001.bin` golden file
        // 2. Convert from double to Q16.16 format on the fly (or load from hex file)
        // 3. Drive in_data with valid strobes
        // 4. Assert lo_data/hi_data matches `l0_001.bin` and `h1_*.bin`
        
        $display("DWT 1D Testbench Initialized.");
        $display("Waiting for stimulus integration...");

        #100;
        $finish;
    end

endmodule
