// =============================================================================
//  de1_soc_top.sv — DE1-SoC Board-Level Top for HPS-FPGA Integration
//  EventVault-R Accelerator
//
//  This module is the TRUE top-level entity for the Quartus project when
//  using Platform Designer (Qsys). It instantiates:
//    1. The Qsys-generated soc_system (HPS + bridges)
//    2. Our evaultr_top accelerator
//  and wires them together via the Lightweight HPS-to-FPGA (LW H2F) bridge.
// =============================================================================

module de1_soc_top (
    // ---- Clock ----
    input  logic        CLOCK_50,

    // ---- HPS DDR3 ----
    output logic [14:0] HPS_DDR3_ADDR,
    output logic [2:0]  HPS_DDR3_BA,
    output logic        HPS_DDR3_CAS_N,
    output logic        HPS_DDR3_CKE,
    output logic        HPS_DDR3_CK_N,
    output logic        HPS_DDR3_CK_P,
    output logic        HPS_DDR3_CS_N,
    output logic [3:0]  HPS_DDR3_DM,
    inout  wire  [31:0] HPS_DDR3_DQ,
    inout  wire  [3:0]  HPS_DDR3_DQS_N,
    inout  wire  [3:0]  HPS_DDR3_DQS_P,
    output logic        HPS_DDR3_ODT,
    output logic        HPS_DDR3_RAS_N,
    output logic        HPS_DDR3_RESET_N,
    input  logic        HPS_DDR3_RZQ,
    output logic        HPS_DDR3_WE_N,

    // ---- HPS UART (directly to UART-to-USB) ----
    input  logic        HPS_UART_RX,
    output logic        HPS_UART_TX,

    // ---- HPS SD Card ----
    output logic        HPS_SD_CLK,
    inout  wire         HPS_SD_CMD,
    inout  wire  [3:0]  HPS_SD_DATA,

    // ---- HPS USB ----
    input  logic        HPS_USB_CLKOUT,
    inout  wire  [7:0]  HPS_USB_DATA,
    input  logic        HPS_USB_DIR,
    input  logic        HPS_USB_NXT,
    output logic        HPS_USB_STP,

    // ---- HPS Ethernet ----
    output logic        HPS_ENET_GTX_CLK,
    inout  wire         HPS_ENET_INT_N,
    output logic        HPS_ENET_MDC,
    inout  wire         HPS_ENET_MDIO,
    input  logic        HPS_ENET_RX_CLK,
    input  logic [3:0]  HPS_ENET_RX_DATA,
    input  logic        HPS_ENET_RX_DV,
    output logic [3:0]  HPS_ENET_TX_DATA,
    output logic        HPS_ENET_TX_EN,

    // ---- HPS I2C (directly to FPGA side) ----
    inout  wire         HPS_I2C1_SCLK,
    inout  wire         HPS_I2C1_SDAT,

    // ---- HPS GPIO / Misc ----
    inout  wire         HPS_CONV_USB_N,
    output logic        HPS_SPIM_CLK,
    output logic        HPS_SPIM_MOSI,
    input  logic        HPS_SPIM_MISO,
    output logic        HPS_SPIM_SS,
    input  logic [1:0]  HPS_KEY,

    // ---- FPGA LEDs (directly accessible) ----
    output logic [9:0]  LEDR
);

    // =========================================================================
    // Internal Wires: Lightweight HPS-to-FPGA Bridge
    // =========================================================================
    // These connect the Qsys HPS component to our evaultr_top accelerator.
    // The Lightweight H2F bridge provides memory-mapped access from the ARM
    // to the FPGA fabric at base address 0xFF200000 in ARM address space.

    logic        h2f_lw_clk;
    logic        h2f_lw_rst_n;

    // AXI-Lite signals from HPS to FPGA (lightweight bridge)
    logic [11:0] h2f_lw_awaddr;
    logic        h2f_lw_awvalid;
    logic        h2f_lw_awready;
    logic [31:0] h2f_lw_wdata;
    logic [3:0]  h2f_lw_wstrb;
    logic        h2f_lw_wvalid;
    logic        h2f_lw_wready;
    logic [1:0]  h2f_lw_bresp;
    logic        h2f_lw_bvalid;
    logic        h2f_lw_bready;
    logic [11:0] h2f_lw_araddr;
    logic        h2f_lw_arvalid;
    logic        h2f_lw_arready;
    logic [31:0] h2f_lw_rdata;
    logic [1:0]  h2f_lw_rresp;
    logic        h2f_lw_rvalid;
    logic        h2f_lw_rready;

    // AXI-Stream pixel data (directly memory-mapped via control registers)
    // The ARM writes pixels one at a time to a data register,
    // which are internally converted to the streaming interface.
    logic [31:0] pixel_write_data;
    logic        pixel_write_valid;
    logic        pixel_write_last;
    logic        pixel_write_ready;

    // AXI-Stream output from FPGA back to readable status registers
    logic [31:0] result_data;
    logic        result_valid;
    logic        result_last;

    // =========================================================================
    // Qsys-generated SoC System
    // =========================================================================
    // This instantiation will be generated by Platform Designer.
    // The port names below match the default Qsys export names.
    // After generating the Qsys system, verify these names match.

    soc_system u_soc (
        // Clock & Reset
        .clk_clk                          (CLOCK_50),
        .reset_reset_n                    (1'b1),

        // HPS DDR3
        .memory_mem_a                     (HPS_DDR3_ADDR),
        .memory_mem_ba                    (HPS_DDR3_BA),
        .memory_mem_cas_n                 (HPS_DDR3_CAS_N),
        .memory_mem_cke                   (HPS_DDR3_CKE),
        .memory_mem_ck                    (HPS_DDR3_CK_P),
        .memory_mem_ck_n                  (HPS_DDR3_CK_N),
        .memory_mem_cs_n                  (HPS_DDR3_CS_N),
        .memory_mem_dm                    (HPS_DDR3_DM),
        .memory_mem_dq                    (HPS_DDR3_DQ),
        .memory_mem_dqs                   (HPS_DDR3_DQS_P),
        .memory_mem_dqs_n                 (HPS_DDR3_DQS_N),
        .memory_mem_odt                   (HPS_DDR3_ODT),
        .memory_mem_ras_n                 (HPS_DDR3_RAS_N),
        .memory_mem_reset_n              (HPS_DDR3_RESET_N),
        .memory_mem_rzq                   (HPS_DDR3_RZQ),
        .memory_mem_we_n                  (HPS_DDR3_WE_N),

        // HPS UART
        .hps_io_hps_io_uart0_inst_RX     (HPS_UART_RX),
        .hps_io_hps_io_uart0_inst_TX     (HPS_UART_TX),

        // HPS SD Card
        .hps_io_hps_io_sdio_inst_CLK     (HPS_SD_CLK),
        .hps_io_hps_io_sdio_inst_CMD     (HPS_SD_CMD),
        .hps_io_hps_io_sdio_inst_D0      (HPS_SD_DATA[0]),
        .hps_io_hps_io_sdio_inst_D1      (HPS_SD_DATA[1]),
        .hps_io_hps_io_sdio_inst_D2      (HPS_SD_DATA[2]),
        .hps_io_hps_io_sdio_inst_D3      (HPS_SD_DATA[3]),

        // HPS USB
        .hps_io_hps_io_usb1_inst_CLK     (HPS_USB_CLKOUT),
        .hps_io_hps_io_usb1_inst_D0      (HPS_USB_DATA[0]),
        .hps_io_hps_io_usb1_inst_D1      (HPS_USB_DATA[1]),
        .hps_io_hps_io_usb1_inst_D2      (HPS_USB_DATA[2]),
        .hps_io_hps_io_usb1_inst_D3      (HPS_USB_DATA[3]),
        .hps_io_hps_io_usb1_inst_D4      (HPS_USB_DATA[4]),
        .hps_io_hps_io_usb1_inst_D5      (HPS_USB_DATA[5]),
        .hps_io_hps_io_usb1_inst_D6      (HPS_USB_DATA[6]),
        .hps_io_hps_io_usb1_inst_D7      (HPS_USB_DATA[7]),
        .hps_io_hps_io_usb1_inst_DIR     (HPS_USB_DIR),
        .hps_io_hps_io_usb1_inst_NXT     (HPS_USB_NXT),
        .hps_io_hps_io_usb1_inst_STP     (HPS_USB_STP),

        // HPS Ethernet
        .hps_io_hps_io_ethernet0_inst_TX_CLK (HPS_ENET_GTX_CLK),
        .hps_io_hps_io_ethernet0_inst_TX_CTL (HPS_ENET_TX_EN),
        .hps_io_hps_io_ethernet0_inst_TXD0   (HPS_ENET_TX_DATA[0]),
        .hps_io_hps_io_ethernet0_inst_TXD1   (HPS_ENET_TX_DATA[1]),
        .hps_io_hps_io_ethernet0_inst_TXD2   (HPS_ENET_TX_DATA[2]),
        .hps_io_hps_io_ethernet0_inst_TXD3   (HPS_ENET_TX_DATA[3]),
        .hps_io_hps_io_ethernet0_inst_RX_CLK (HPS_ENET_RX_CLK),
        .hps_io_hps_io_ethernet0_inst_RX_CTL (HPS_ENET_RX_DV),
        .hps_io_hps_io_ethernet0_inst_RXD0   (HPS_ENET_RX_DATA[0]),
        .hps_io_hps_io_ethernet0_inst_RXD1   (HPS_ENET_RX_DATA[1]),
        .hps_io_hps_io_ethernet0_inst_RXD2   (HPS_ENET_RX_DATA[2]),
        .hps_io_hps_io_ethernet0_inst_RXD3   (HPS_ENET_RX_DATA[3]),
        .hps_io_hps_io_ethernet0_inst_MDIO   (HPS_ENET_MDIO),
        .hps_io_hps_io_ethernet0_inst_MDC    (HPS_ENET_MDC),

        // HPS SPI
        .hps_io_hps_io_spim1_inst_CLK    (HPS_SPIM_CLK),
        .hps_io_hps_io_spim1_inst_MOSI   (HPS_SPIM_MOSI),
        .hps_io_hps_io_spim1_inst_MISO   (HPS_SPIM_MISO),
        .hps_io_hps_io_spim1_inst_SS0    (HPS_SPIM_SS),

        // HPS I2C
        .hps_io_hps_io_i2c1_inst_SDA     (HPS_I2C1_SDAT),
        .hps_io_hps_io_i2c1_inst_SCL     (HPS_I2C1_SCLK),

        // HPS GPIO
        .hps_io_hps_io_gpio_inst_GPIO53  (HPS_CONV_USB_N),

        // Lightweight HPS-to-FPGA Bridge (directly to our accelerator)
        .hps_0_h2f_lw_axi_clock_clk      (h2f_lw_clk),
        .hps_0_h2f_lw_axi_master_awaddr  (h2f_lw_awaddr),
        .hps_0_h2f_lw_axi_master_awvalid (h2f_lw_awvalid),
        .hps_0_h2f_lw_axi_master_awready (h2f_lw_awready),
        .hps_0_h2f_lw_axi_master_wdata   (h2f_lw_wdata),
        .hps_0_h2f_lw_axi_master_wstrb   (h2f_lw_wstrb),
        .hps_0_h2f_lw_axi_master_wvalid  (h2f_lw_wvalid),
        .hps_0_h2f_lw_axi_master_wready  (h2f_lw_wready),
        .hps_0_h2f_lw_axi_master_bresp   (h2f_lw_bresp),
        .hps_0_h2f_lw_axi_master_bvalid  (h2f_lw_bvalid),
        .hps_0_h2f_lw_axi_master_bready  (h2f_lw_bready),
        .hps_0_h2f_lw_axi_master_araddr  (h2f_lw_araddr),
        .hps_0_h2f_lw_axi_master_arvalid (h2f_lw_arvalid),
        .hps_0_h2f_lw_axi_master_arready (h2f_lw_arready),
        .hps_0_h2f_lw_axi_master_rdata   (h2f_lw_rdata),
        .hps_0_h2f_lw_axi_master_rresp   (h2f_lw_rresp),
        .hps_0_h2f_lw_axi_master_rvalid  (h2f_lw_rvalid),
        .hps_0_h2f_lw_axi_master_rready  (h2f_lw_rready)
    );

    // =========================================================================
    // EventVault-R Accelerator
    // =========================================================================
    // Our existing accelerator, now connected to the HPS via the LW bridge.

    assign h2f_lw_clk = CLOCK_50;

    evaultr_top #(
        .PIXEL_W(16),
        .AXI_ADDR_W(12),
        .AXI_DATA_W(32)
    ) accel_inst (
        .clk        (CLOCK_50),
        .rst_n      (h2f_lw_rst_n),

        // AXI-Lite Control Plane (from HPS lightweight bridge)
        .s_axi_awaddr  (h2f_lw_awaddr),
        .s_axi_awvalid (h2f_lw_awvalid),
        .s_axi_awready (h2f_lw_awready),
        .s_axi_wdata   (h2f_lw_wdata),
        .s_axi_wstrb   (h2f_lw_wstrb),
        .s_axi_wvalid  (h2f_lw_wvalid),
        .s_axi_wready  (h2f_lw_wready),
        .s_axi_bresp   (h2f_lw_bresp),
        .s_axi_bvalid  (h2f_lw_bvalid),
        .s_axi_bready  (h2f_lw_bready),
        .s_axi_araddr  (h2f_lw_araddr),
        .s_axi_arvalid (h2f_lw_arvalid),
        .s_axi_arready (h2f_lw_arready),
        .s_axi_rdata   (h2f_lw_rdata),
        .s_axi_rresp   (h2f_lw_rresp),
        .s_axi_rvalid  (h2f_lw_rvalid),
        .s_axi_rready  (h2f_lw_rready),

        // Pixel data — ARM writes pixel values to register 0x04,
        // which are internally forwarded to the AXI-Stream interface.
        .s_axis_tdata  (pixel_write_data),
        .s_axis_tvalid (pixel_write_valid),
        .s_axis_tlast  (pixel_write_last),
        .s_axis_tready (pixel_write_ready),

        // DWT results output
        .m_axis_tdata  (result_data),
        .m_axis_tvalid (result_valid),
        .m_axis_tlast  (result_last),
        .m_axis_tready (1'b1)           // Always accept output for now
    );

    // =========================================================================
    // Status LEDs
    // =========================================================================
    assign LEDR[0] = result_valid;   // Blinks when DWT is producing output
    assign LEDR[1] = pixel_write_ready; // Shows accelerator is ready for data
    assign LEDR[9:2] = 8'b0;

    // =========================================================================
    // Reset Synchronizer
    // =========================================================================
    reg [2:0] rst_sync;
    always_ff @(posedge CLOCK_50) begin
        rst_sync <= {rst_sync[1:0], 1'b1};
    end
    assign h2f_lw_rst_n = rst_sync[2];

endmodule
